# Generated by Django 5.0 on 2023-12-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='球場名稱')),
                ('court_type', models.CharField(choices=[('grass', '草地'), ('hard', '硬地'), ('clay', '泥地'), ('carpet', '地毯')], max_length=10, verbose_name='球場型態')),
                ('city', models.CharField(max_length=100, verbose_name='所在城市')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
